Jobportal_design/Controllers/OrgController.cs
using Jobportal_design.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Net;
using System.Net.Http.Headers;
using Microsoft.Extensions.Configuration;
using AspNetCoreHero.ToastNotification.Abstractions;
using System.Net.Mail;
using System.Data;
using ExcelDataReader;
namespace Jobportal_design.Controllers
{
    public class OrgController : Controller
    {
        private  IWebHostEnvironment Environment;
        private IConfiguration _Configure;
        string apiBaseUrl;
        private readonly INotyfService _notyf;
        public OrgController(IWebHostEnvironment _environment, IConfiguration configuration, INotyfService notyf)
        {
            _notyf = notyf;
            Environment = _environment;
            _Configure = configuration;
            apiBaseUrl = _Configure.GetValue<string>("WebAPIBaseUrl");
        }
        //public OrgController()
        //{
        //    ViewBag.state = "";
        //    ViewBag.country = "";
        //    ViewBag.currency = "";
        //    ViewBag.district = "";
        //    ViewBag.org_cat = "";


        //}
        public IActionResult AddOrg()
        {
            List<State_tbl> state = new List<State_tbl>();
            List<County_tbl> county = new List<County_tbl>();
            List<District_tbl> district = new List<District_tbl>();
            List<Currency_tbl> currency = new List<Currency_tbl>();
            List<Org_cat> org_cat = new List<Org_cat>();
            List<Location_tbl> location = new List<Location_tbl>();
            string apiUrl = apiBaseUrl + "/State/getAllActiveState";
            string apiUrl1 = apiBaseUrl + "/County/getAllActiveCounty";
            string apiUrl2 = apiBaseUrl + "/Currency/getAllActiveCurrency";
            string apiUrl3 = apiBaseUrl + "/District/getAllActiveDistrict";
            string apiUrl4 = apiBaseUrl + "/Org_cat/getAllActiveOrgCategory";
            string apiUrl5 = apiBaseUrl + "/Location/getAllActiveLocations";

            HttpClient client = new HttpClient();
            HttpResponseMessage response = client.GetAsync(apiUrl).Result;
            if (response.IsSuccessStatusCode)
            {
                state = JsonConvert.DeserializeObject<List<State_tbl>>(response.Content.ReadAsStringAsync().Result);
            }
            ViewBag.state = state;

            HttpResponseMessage response1 = client.GetAsync(apiUrl1).Result;
            if (response.IsSuccessStatusCode)
            {
                county = JsonConvert.DeserializeObject<List<County_tbl>>(response1.Content.ReadAsStringAsync().Result);
            }
            ViewBag.county = county;

            HttpResponseMessage response2 = client.GetAsync(apiUrl2).Result;
            if (response.IsSuccessStatusCode)
            {
                currency = JsonConvert.DeserializeObject<List<Currency_tbl>>(response2.Content.ReadAsStringAsync().Result);
            }
            ViewBag.currency = currency;

            HttpResponseMessage response3 = client.GetAsync(apiUrl3).Result;
            if (response.IsSuccessStatusCode)
            {
                district = JsonConvert.DeserializeObject<List<District_tbl>>(response3.Content.ReadAsStringAsync().Result);
            }
            ViewBag.district = district;

            HttpResponseMessage response4 = client.GetAsync(apiUrl4).Result;
            if (response4.IsSuccessStatusCode)
            {
                org_cat = JsonConvert.DeserializeObject<List<Org_cat>>(response4.Content.ReadAsStringAsync().Result);
            }
            ViewBag.org_cat = org_cat;

            HttpResponseMessage response5 = client.GetAsync(apiUrl5).Result;
            if (response5.IsSuccessStatusCode)
            {
                location = JsonConvert.DeserializeObject<List<Location_tbl>>(response5.Content.ReadAsStringAsync().Result);
            }
            ViewBag.location = location;
            return View();
        }
        public IActionResult Orglist1()
        {
            List<Org_physical> customers = new List<Org_physical>();
            string apiUrl = apiBaseUrl + "/Org/getAll";

            HttpClient client = new HttpClient();
            HttpResponseMessage response = client.GetAsync(apiUrl).Result;
            if (response.IsSuccessStatusCode)
            {
                customers = JsonConvert.DeserializeObject<List<Org_physical>>(response.Content.ReadAsStringAsync().Result);
            }

            return View(customers);
        }

        public async Task<ActionResult> Orglist(int county_id,int dist_id, int org_cat_id, string search)
        {
            List<District_tbl> district = new List<District_tbl>();
            List<Org_cat> org_cat = new List<Org_cat>();
            List<Org_physical> customers = new List<Org_physical>();

            string apiUrl = apiBaseUrl + "/Org/getAllOrgwithJobcount/";
            string apiUrl3 = apiBaseUrl + "/District/getAllActiveDistrict";
            string apiUrl4 = apiBaseUrl + "/Org_cat/getAllActiveOrgCategory";

            string categorytext = org_cat_id.ToString();
            string city = dist_id.ToString();
            string county = county_id.ToString();
            string searchval = search;

            if (string.IsNullOrEmpty(categorytext))
            {
                categorytext = "0";
            }
            if (string.IsNullOrEmpty(city))
            {
                city = "0";
            }
            if (string.IsNullOrEmpty(county))
            {
                county = "0";
            }
            if (string.IsNullOrEmpty(searchval))
            {
                searchval = "all";
            }

            HttpClient client = new HttpClient();


            HttpResponseMessage response3 = client.GetAsync(apiUrl3).Result;
            if (response3.IsSuccessStatusCode)
            {
                district = JsonConvert.DeserializeObject<List<District_tbl>>(response3.Content.ReadAsStringAsync().Result);
            }
            ViewBag.district = district;

            HttpResponseMessage response4 = client.GetAsync(apiUrl4).Result;
            if (response4.IsSuccessStatusCode)
            {
                org_cat = JsonConvert.DeserializeObject<List<Org_cat>>(response4.Content.ReadAsStringAsync().Result);
            }
            ViewBag.org_cat = org_cat;

            HttpResponseMessage response = client.GetAsync(apiUrl + categorytext +"/"+ county+ "/" + city + "/" + searchval).Result;
            
            if (response.IsSuccessStatusCode)
            {
                customers = JsonConvert.DeserializeObject<List<Org_physical>>(response.Content.ReadAsStringAsync().Result);
            }

            ViewBag.orgCount = customers.Count();
            
            ViewBag.searchText = search;
            return View(customers);
        }
        public async Task<ActionResult> OrglistPartialView(int county_id, int dist_id, int org_cat_id, string search)
        {
            List<District_tbl> district = new List<District_tbl>();
            List<Org_cat> org_cat = new List<Org_cat>();
            List<Org_physical> customers = new List<Org_physical>();

            string apiUrl = apiBaseUrl + "/Org/getAllOrgwithJobcount/";
            string apiUrl3 = apiBaseUrl + "/District/getAllActiveDistrict";
            string apiUrl4 = apiBaseUrl + "/Org_cat/getAllActiveOrgCategory";

            string categorytext = org_cat_id.ToString();
            string city = dist_id.ToString();
            string county = county_id.ToString();
            string searchval = search;

            if (string.IsNullOrEmpty(categorytext))
            {
                categorytext = "0";
            }
            if (string.IsNullOrEmpty(city))
            {
                city = "0";
            }
            if (string.IsNullOrEmpty(county))
            {
                county = "0";
            }
            if (string.IsNullOrEmpty(searchval))
            {
                searchval = "all";
            }

            HttpClient client = new HttpClient();


           

            HttpResponseMessage response = client.GetAsync(apiUrl + categorytext + "/" + county + "/" + city + "/" + searchval).Result;

            if (response.IsSuccessStatusCode)
            {
                customers = JsonConvert.DeserializeObject<List<Org_physical>>(response.Content.ReadAsStringAsync().Result);

            }

            ViewBag.orgCount = customers.Count();

            ViewBag.searchText = search;
            
            return PartialView("OrglistPartialView", customers);
        }
        public async Task<ActionResult> OrganizationList(int county_id,int dist_id, int org_cat_id, string search)
        {
            List<District_tbl> district = new List<District_tbl>();
            List<Org_cat> org_cat = new List<Org_cat>();
            List<Org_physical> customers = new List<Org_physical>();

            string apiUrl = apiBaseUrl + "/Org/getAllOrgwithJobcount/";
            string apiUrl3 = apiBaseUrl + "/District/getAllActiveDistrict";
            string apiUrl4 = apiBaseUrl + "/Org_cat/getAllActiveOrgCategory";

            string categorytext = org_cat_id.ToString();
            string city = dist_id.ToString();
            string searchval = search;
            string county = county_id.ToString();
            if (string.IsNullOrEmpty(categorytext))
            {
                categorytext = "0";
            }
            if (string.IsNullOrEmpty(city))
            {
                city = "0";
            }
            if (string.IsNullOrEmpty(county))
            {
                county = "0";
            }
            if (string.IsNullOrEmpty(searchval))
            {
                searchval = "all";
            }

Jobportal_design/Views/Org/Changepassword.cshtml
@model IEnumerable<Jobportal_design.Models.Employer>

@{
    ViewData["Title"] = "Change Password";
    Layout = "~/Views/Shared/_Layout.cshtml";
    //Layout = null;
}

<section class="login-register">
    <div class="container">
        <div class="row login-register-cover">
            <div class="col-lg-4 col-md-6 col-sm-12 mx-auto">
                <div class="text-center">
                    <h3 class="mt-10 mb-5 text-brand-1">Reset Your Password</h3>
                    <p class="font-sm text-muted mb-30">
                        Change your Account Password and Login again..

                    </p>
                </div>
                @using (Html.BeginForm("UpdatePassword", "Org", FormMethod.Post, new { @id = "CNenrollment" }))
                {
                    <form class="login-register text-start mt-20" action="#">
                        <div class="form-group">
                            <label class="form-label" for="input-1">Old password *</label>
                            <input class="form-control" type="text" required id="org_password" name="org_password" placeholder="********">
                        </div>
                        <p style="color: red;">@TempData["Oldpassword"]</p>
                        <div class="form-group">
                            <label class="form-label" for="input-1">New Password *</label>
                            <input class="form-control" id="new_password" name="new_password" type="text" required="" placeholder="********">
                        </div>
                        <div class="form-group">
                            <label class="form-label" for="input-1">Re-type Password *</label>
                            <input class="form-control" id="retype_password" name="retype_password" type="text" required="" placeholder="********">
                        </div>
                        <p style="color: red;">@TempData["Repassword"]</p>
                        <div class="form-group">
                            <button class="btn btn-brand-1 hover-up w-100" type="submit" name="continue">Save Password</button>
                        </div>
                    </form>

                }
            </div>
            <div class="img-1 d-none d-lg-block"><img class="shape-1" src="~/imgs/page/login-register/img-5.svg" alt="JobBox"></div>
            <div class="img-2"><img src="~/imgs/page/login-register/img-3.svg" alt="JobBox"></div>
        </div>
    </div>
</section>

Jobportal_design/Views/Org/Org_employee.cshtml
@model IEnumerable<Jobportal_design.Models.Employer>
@{
    ViewData["Title"] = "View";
    
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<link rel="stylesheet" type="text/css" href="~/admin/assets/extra-libs/multicheck/multicheck.css">
<link href="~/admin/assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div class="row">
    <div class="col-12">
        <input type="button" class="btn btn-primary" style="float: right;" value="JOBS" onclick="location.href='@Url.Action("Org_JobList", "Employer")'" />

        <input type="button" class="btn btn-primary" style="float: right;" value="Add Employee" onclick="location.href='@Url.Action("AddEmployer", "Employer")'" />


        <div class="card">

            <div class="card-body">

                <h5 class="card-title">Employee Details</h5>
                <div class="table-responsive">
                    <table id="zero_config" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Mobile No:</th>
                                <th>Email</th>

                                <th>Registration Date</th>

                                <th>Status</th>
                               
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                string registration_date = item.registration_date.ToString("MM/dd/yyyy");
                                bool str = item.status;
                                string str1 = str.ToString();
                               
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.e_name)
                                </td>




                                <td>
                                    @Html.DisplayFor(modelItem => item.last_name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.contact1)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.email_id)
                                </td>

                                <td>
                                    @Html.DisplayFor(modelItem => registration_date)
                                </td>

                                <td>
                                    @Html.DisplayFor(modelItem => item.isactive)
                                </td>

                                <!--<td>-->
                                @*@Html.ActionLink("Change Password", "Admin_passwordchange", "Employer", new { id = @item.id }, new { @class = "btn btn-primary" })*@
                                <!--<p style="text-decoration:underline;"><a href="@Url.Action("Admin_passwordchange", "Employer",new { id = @item.id })">@Html.DisplayFor(modelItem => item.e_password)</a></p>
    </td>-->
                                <td>
                                    @Html.ActionLink("Jobs Posted", "PostedJobsList", "Employer", new { id = @item.id }, new { @class = "btn btn-secondary" })
                                </td>

                                <td>
                                    @*@Html.ActionLink("EDIT", "EditCountry", "Country", new { id = @item.id }, new { @class = "genric-btn info circle small" })
            @Html.ActionLink("DELETE", "DeleteCountry", "Country", new { id = @item.id }, new { @class = "genric-btn danger circle small" })*@
                                    @*<a href="@Url.Action("Admin_emp_EditProfile", "Employer",new { id = @item.id })" class="edit" title="Edit" data-toggle="tooltip"><i class="fa fa-pencil" style="font-size: 24px;color:lightblue"></i></a>*@
                                    <a href="@Url.Action("Delete_admin_emp", "Employer",new { id = @item.id })" class="delete" title="Delete" data-toggle="tooltip"><i class="fa fa-trash-o" style="font-size: 24px; color: red;"></i></a>
                                </td>

                                

                            </tr>
                            }


                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</div>




<script>
    /****************************************
     *       Basic Table                   *
     ****************************************/
    $('#zero_config').DataTable();
</script>

Jobportal_design/Views/Org/Orglist.cshtml
@model IEnumerable<Jobportal_design.Models.Org_physical>

@{
    ViewData["Title"] = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
    //Layout = null;

}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<link href="~/css/new-style.css" rel="stylesheet" />
@*<link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">*@

@*<a href="#" class="ml-5" style="color: #85c440;" id="btnBack"><i class="fi fi-rr-arrow-left" style="color: #85c440; font-size: 13px;"></i><span style="color: black;">&nbsp;Back</span></a><section class="section-box-2">*@
<div class="col-lg-12 text-left">

    <ul class="breadcrumbs pb-2">
        <li><a class="home-icon" href="@Url.Action("Index", "Home")">Home</a></li>
        <li><a class="home-icon01" href="@Url.Action("Orglist", "Org")">Organizations</a></li>
    </ul>
</div>
<section>
    <div class="container">
        <div class="banner-hero banner-single banner-single-bg">
            <div class="block-banner text-center">
                <h3 class="wow animate__animated animate__fadeInUp">
                    <span class="color-brand-2"> Browse Organizations</span>                    @*<div>@ViewBag.role</div>*@
                </h3>
                <div class="font-sm color-text-paragraph-2 mt-10 wow animate__animated animate__fadeInUp" data-wow-delay=".1s">Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero repellendus magni, <br class="d-none d-xl-block">atque delectus molestias quis?</div>
                <div class="form-find text-start mt-40 wow animate__animated animate__fadeInUp" data-wow-delay=".2s">
                    @using (Html.BeginForm("OrglistPartialView", "Org", FormMethod.Post, new { enctype = "multipart/form-data", @id = "filterForm" }))
                    {
                        <form>
                            <div class="box-industry">
                                @Html.DropDownList("org_cat_id", new SelectList(ViewBag.org_cat, "id", "category_name"), "-Category-", new { id = "dd_child", @class = "form-input mr-10 select-active input-industry" })
                            </div>
                            @Html.DropDownList("dist_id", new SelectList(ViewBag.district, "id", "dist_name"), "--City--", new { id = "dd_child1", @class = "form-input mr-10 select-active" })
                            <input class="form-input input-keysearch mr-10" type="text" id="search" name="search" value="@ViewBag.searchText" placeholder="Enter Organization Name...">
                            <input type="submit" class="btn btn-default btn-find font-sm" id="searchpartialview" value="Search" />
                        </form>
                    }

                </div>
            </div>
        </div>
    </div>
</section>



<div id="OrglistPartialView">
    @await Html.PartialAsync("OrglistPartialView")
    @*@Html.PartialAsync("FindJobPartialView", "Home")*@
</div>



<section class="section-box mt-50 mb-20">
    <div class="container">
        <div class="box-newsletter">
            <div class="row">
                <div class="col-xl-3 col-12 text-center d-none d-xl-block"><img src="~/imgs/template/newsletter-left.png" alt="joxBox"></div>
                <div class="col-lg-12 col-xl-6 col-12">
                    <h2 class="text-md-newsletter text-center">New Things Will Always<br> Update Regularly</h2>
                    <div class="box-form-newsletter mt-40">
                        <form class="form-newsletter">
                            <input class="input-newsletter" type="text" value="" placeholder="Enter your email here">
                            <button class="btn btn-default font-heading icon-send-letter">Subscribe</button>
                        </form>
                    </div>
                </div>
                <div class="col-xl-3 col-12 text-center d-none d-xl-block"><img src="~/imgs/template/newsletter-right.png" alt="joxBox"></div>
            </div>
        </div>
    </div>
</section>


@*<script src="js/noUISlider.js"></script>*@
<script src="js/slider.js"></script>

@section scripts {
    <script type="text/javascript">
        $("#btnBack").click(function () {
            window.history.back();
        });

        $(function () {
            $('#filterForm').submit(function (event) {                
                event.preventDefault();
                var filterData = $(this).serialize();
                $('#preloader-active').show();
                $.get('/Org/OrglistPartialView', filterData, function (result) {
                    $('#OrglistPartialView').html(result);
                    $('#preloader-active').hide();
                });
            });
        });        

    </script>



    <script>
        $.fn.pageMe = function (opts) {
            var $this = this,
                defaults = {
                    perPage: 15,
                    showPrevNext: false,
                    hidePageNumbers: false
                },
                settings = $.extend(defaults, opts);
            console.log(settings)
            var listElement = $this;
            var perPage = settings.perPage;
            var children = listElement.children();
            var pager = $('.pager');

            if (typeof settings.childSelector != "undefined") {
                children = listElement.find(settings.childSelector);
            }

            if (typeof settings.pagerSelector != "undefined") {
                pager = $(settings.pagerSelector);
            }

            var numItems = children.size();
            var numPages = Math.ceil(numItems / perPage);

            pager.data("curr", 0);

            if (settings.showPrevNext) {
                $('<li><a href="#" class="pager-prev"></a></li>').appendTo(pager);
            }

            var curr = 0;
            // Added class and id in li start
            while (numPages > curr && (settings.hidePageNumbers == false)) {
                $('<li id="pg' + (curr + 1) + '" class="pg"><a href="#" class="page_link">' + (curr + 1) + '</a></li>').appendTo(pager);
                curr++;
            }
            // Added class and id in li end

            if (settings.showPrevNext) {
                $('<li><a href="#" class="pager-next"></a></li>').appendTo(pager);
            }

            pager.find('.page_link:first').addClass('active');
            pager.find('.pager-prev').hide();
            if (numPages <= 1) {
                pager.find('.pager-next').hide();
            }
           // pager.children().eq(1).addClass("active");

            children.hide();
            children.slice(0, perPage).show();
            if (numPages > 3) {
                $('.pg').hide();
                $('#pg1,#pg2,#pg3').show();
                $("#pg3").after($("<li class='ell'>").html("<span>...</span>"));
            }

            pager.find('li .page_link').click(function () {
                var clickedPage = $(this).html().valueOf() - 1;
                goTo(clickedPage, perPage);
                return false;
            });
            pager.find('li .pager-prev').click(function () {
                previous();
                return false;
            });
            pager.find('li .pager-next').click(function () {
                next();
                return false;
            });

            function previous() {
                var goToPage = parseInt(pager.data("curr")) - 1;
                $('.pg').children().eq(goToPage + 1).removeClass("active");
                goTo(goToPage);
            }

            function next() {
                goToPage = parseInt(pager.data("curr")) + 1;
                goTo(goToPage);
            }

            function goTo(page) {
                var startAt = page * perPage,
                    endOn = startAt + perPage;

                // Added few lines from here start

                $('.pg').hide();
                $(".ell").remove();
                var prevpg = $("#pg" + page).show();
                var currpg = $("#pg" + (page + 1)).show();
                var nextpg = $("#pg" + (page + 2)).show();
                if (prevpg.length == 0) nextpg = $("#pg" + (page + 3)).show();
                if (prevpg.length == 1 && nextpg.length == 0) {
                    prevpg = $("#pg" + (page - 1)).show();
                }
                $("#pg1").show()
                if (curr > 3) {
                    if (page > 1) prevpg.before($("<li class='ell'>").html("<span>...</span>"));
                    if (page < curr - 2) nextpg.after($("<li class='ell'>").html("<span>...</span>"));
                }

                if (page <= numPages - 3) {
                    $("#pg" + numPages.toString()).show();
                }
                currpg.addClass("active").siblings().removeClass("active");
                // Added few lines till here end


                children.css('display', 'none').slice(startAt, endOn).show();

                if (page >= 1) {
                    pager.find('.pager-prev').show();
                } else {
                    pager.find('.pager-prev').hide();
                }

                if (page < (numPages - 1)) {
                    pager.find('.pager-next').show();
                } else {
                    pager.find('.pager-next').hide();
                }

                pager.data("curr", page);
                if ($('.pg').children().eq(page - 1).hasClass("active")) {
                    $('.pg').children().eq(page - 1).removeClass("active");
                }
                if ($('.pg').children().eq(page + 1).hasClass("active")) {
                    $('.pg').children().eq(page + 1).removeClass("active");
                }
                $('.pg').children().eq(page).addClass("active");
                var fp = (page * 15)+1;
                var tp = (page+1) * 15;
                $("#startP").text(fp.toString());
                if(tp<@ViewBag.orgCount)
                $("#endP").text(tp.toString());
                else
                $("#endP").text(@ViewBag.orgCount);
                $("#currentP").text((page+1).toString());
                $("#totalP").text(numPages.toString());
                window.scrollTo(0, 250);

            }
        };

        @*$(document).ready(function () {
            $("#currentP").text("1");
                $("#totalP").text(Math.ceil(@ViewBag.orgCount/15).toString());
            $('#myTable').pageMe({
                pagerSelector: '#myPager',
                showPrevNext: true,
                hidePageNumbers: false,
                perPage: 15
            });

        });*@
    </script>

}
<script>
     function callChangefunc() {

         var searchval = document.getElementById("search").value;
         var city = document.getElementById("dd_child1").value;
         var categorytext = document.getElementById("dd_child").value;

         //alert(exptext);

         var url = "@Url.Action("Orglist", "Org")" + "?searchval=" + searchval + "&city=" + city + "&categorytext=" + categorytext;

            window.location.href = url;


        }
</script>

<style>
    .slides-sec01 #myTable .info-text {
        height: 195px;
        overflow: hidden;
        overflow-y: auto;
    }

        .slides-sec01 #myTable .info-text h5 {
            line-height: 20px;
            display: -webkit-box;
            -webkit-line-clamp: 2;
            -webkit-box-orient: vertical;
            overflow: hidden;
            text-overflow: ellipsis;
        }
</style>